apiVersion: v1
kind: Service
metadata:
  name: network-log-analyzer-service
spec:
  type: NodePort
  selector:
    app: network-log-analyzer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
